
version: '3.1'

services:

  db:
    image: postgres
    # restart: always
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: repco
      POSTGRES_USER: repco
      POSTGRES_DB: repco

  meilisearch:
    image: getmeili/meilisearch:v1.0
    ports: 
      - 7700:7700
    environment:
      - MEILI_MASTER_KEY=${MEILISEARCH_API_KEY}
    volumes:
      - ./data/meilisearch:/meili_data
