
version: '3.1'

services:
  app:
    build:
      context: '..'
      dockerfile: './docker/Dockerfile'
    ports:
      - 8766:8765
    environment:
      - DATABASE_URL=postgresql://repco:repco@db:5432/repco
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres
    # volumes:
    #     - "/tmp/repco/postgres:/var/lib/postgresql/data"
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: repco
      POSTGRES_USER: repco
      POSTGRES_DB: repco
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U repco"]
      interval: 5s
      timeout: 5s
      retries: 5
