version: "3.3"

services:

  peertube:
    # If you don't want to use the official image and build one from sources:
    # build:
    #   context: .
    #   dockerfile: ./support/docker/production/Dockerfile.bullseye
    image: chocobozzz/peertube:production-bullseye
    env_file:
      - .env
    ports:
    #  - "1935:1935" # Comment if you don't want to use the live feature
      - "${PT_PORT:-9000}:9000" # Uncomment if you use another webserver/proxy or test PeerTube in local, otherwise not suitable for production
    volumes:
     # - ${VOLUME_ROOT:-./docker-volume}/assets:/app/client/dist
      - ${VOLUME_ROOT:-./docker-volume}/data:/data
      - ${VOLUME_ROOT:-./docker-volume}/config:/config
    depends_on:
      - postgres
      - redis
      # - postfix
    environment:
      - PEERTUBE_WEBSERVER_PORT=${PT_PORT:-9000}
    restart: "always"
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: postgres:13-alpine
    env_file:
      - .env
    volumes:
      - ${VOLUME_ROOT:-./docker-volume}/db:/var/lib/postgresql/data
    restart: "always"

  redis:
    image: redis:6-alpine
    volumes:
      - ${VOLUME_ROOT:-./docker-volume}/redis:/data
    restart: "always"

  postfix:
    image: mwader/postfix-relay
    env_file:
      - .env
    volumes:
      - ${VOLUME_ROOT:-./docker-volume}/opendkim/keys:/etc/opendkim/keys
    restart: "always"

